import { redirect } from "next/navigation";
import { query } from "@/lib/db";
import { requireUser } from "@/lib/security";
import { configurePayrollJournalAction, configurePayrollMappingAction } from "./setup-actions";
import { createEmployeeAction, createJobTitleAction, createSalaryAgreementAction, updateEmployeeAction, updateJobTitleAction } from "./employee-actions";
import { createSalaryAdvanceAction, reverseSalaryAdvanceAction } from "./advance-actions";
import { addPayrollAdjustmentAction, approvePayrollRunAction, createPayrollRunAction, lockPayrollRunAction, payPayrollRunAction, removePayrollAdjustmentAction, returnPayrollRunToDraftAction, reversePayrollPaymentAction, submitPayrollRunAction } from "./run-actions";

type Row = Record<string, any>;
function iso(value: unknown) { return String(value ?? "").slice(0, 10); }
function title(value: unknown) { return String(value ?? "").replaceAll("_", " ").replace(/\b\w/g, (m) => m.toUpperCase()); }
function money(value: unknown, currency = "USD") {
  const n = Number(value ?? 0);
  try { return new Intl.NumberFormat("en-US", { style: "currency", currency, minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number.isFinite(n) ? n : 0); }
  catch { return currency + " " + (Number.isFinite(n) ? n : 0).toFixed(2); }
}

export default async function PayrollPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const auth = await requireUser();
  const { error, success } = await searchParams;
  const can = (permission: string) => auth.permissions.includes(permission);
  const payrollPermissions = ["employees.view","employees.manage","payroll.view","payroll.manage","payroll.approve","payroll.lock","payroll.pay","salary_advances.manage"];
  const canSeeData = payrollPermissions.some(can);
  if (!canSeeData && !can("accounting.mapping")) redirect("/forbidden");

  const today = (await query<{today:string}>("select (now() at time zone 'Asia/Beirut')::date::text as today")).rows[0]?.today ?? "";
  const currencySetting = (await query<{currency:string|null}>("select value #>> '{}' as currency from app_setting where key='currency'")).rows[0]?.currency ?? "USD";

  const [journalsR, configR, rolesR, accountsR, jobsR, employeesR, salaryR, advancesR, schedulesR, runsR, itemsR, paymentsR, cashR, ledgerR] = await Promise.all([
    (can("accounting.mapping") || canSeeData) ? query<Row>("select id,code,name from journal where status='active' order by code") : Promise.resolve({rows:[]} as any),
    (can("accounting.mapping") || canSeeData) ? query<Row>("select payroll_journal_id from accounting_configuration where id=1") : Promise.resolve({rows:[]} as any),
    (can("accounting.mapping") || canSeeData) ? query<Row>("select d.role_key,d.name,d.description,d.required_category,m.account_id,a.code account_code,a.name account_name from accounting_role_definition d left join accounting_mapping m on m.role_key=d.role_key left join account a on a.id=m.account_id where d.role_key=any($1::text[]) order by case d.role_key when 'payroll_expense' then 1 when 'salary_payable' then 2 else 3 end", [["payroll_expense","salary_payable","salary_advance"]]) : Promise.resolve({rows:[]} as any),
    (can("accounting.mapping") || canSeeData) ? query<Row>("select a.id,a.code,a.name,a.currency,t.category from account a join account_type t on t.id=a.account_type_id where a.status='active' and a.allow_posting=true order by a.code") : Promise.resolve({rows:[]} as any),
    canSeeData ? query<Row>("select * from job_title order by status,name") : Promise.resolve({rows:[]} as any),
    canSeeData ? query<Row>("select e.*,j.name job_title,s.monthly_salary current_salary,s.currency salary_currency,s.effective_from salary_effective_from from employee e left join job_title j on j.id=e.job_title_id left join lateral (select * from employee_salary_agreement x where x.employee_id=e.id and x.effective_from<=$1 order by x.effective_from desc limit 1) s on true order by e.status,e.last_name,e.first_name", [today]) : Promise.resolve({rows:[]} as any),
    canSeeData ? query<Row>("select h.*,e.employee_number,e.first_name,e.last_name from employee_salary_history h join employee e on e.id=h.employee_id order by e.last_name,e.first_name,h.effective_from desc") : Promise.resolve({rows:[]} as any),
    canSeeData ? query<Row>("select b.*,e.employee_number,e.first_name,e.last_name,c.display_name payment_account_name from salary_advance_balance b join salary_advance a on a.id=b.id join employee e on e.id=b.employee_id join cash_bank_account c on c.account_id=a.payment_account_id order by b.advance_date desc,a.created_at desc") : Promise.resolve({rows:[]} as any),
    canSeeData ? query<Row>("select s.*,a.employee_id,coalesce(sum(x.amount),0)::numeric(14,2) applied_amount from salary_advance_repayment_schedule s join salary_advance a on a.id=s.salary_advance_id left join salary_advance_repayment_allocation x on x.repayment_schedule_id=s.id group by s.id,a.employee_id order by s.due_on,s.installment_number") : Promise.resolve({rows:[]} as any),
    canSeeData ? query<Row>("select * from payroll_run_summary order by period_end desc,run_number desc") : Promise.resolve({rows:[]} as any),
    canSeeData ? query<Row>("select i.*,r.run_number,r.status run_status,r.currency,r.pay_date,e.employee_number,e.first_name,e.last_name,s.effective_from salary_effective_from,coalesce(json_agg(json_build_object('id',a.id,'type',a.adjustment_type,'description',a.description,'amount',a.amount) order by a.created_at) filter(where a.id is not null),'[]') adjustments,coalesce((select json_agg(json_build_object('advanceNumber',sa.advance_number,'installment',rs.installment_number,'dueOn',rs.due_on,'amount',x.amount) order by rs.due_on,rs.installment_number) from salary_advance_repayment_allocation x join salary_advance_repayment_schedule rs on rs.id=x.repayment_schedule_id join salary_advance sa on sa.id=rs.salary_advance_id where x.payroll_run_item_id=i.id),'[]') repayments from payroll_run_item i join payroll_run r on r.id=i.payroll_run_id join employee e on e.id=i.employee_id join employee_salary_agreement s on s.id=i.salary_agreement_id left join payroll_adjustment a on a.payroll_run_item_id=i.id group by i.id,r.id,e.id,s.id order by r.period_end desc,e.last_name,e.first_name") : Promise.resolve({rows:[]} as any),
    canSeeData ? query<Row>("select p.*,r.run_number,c.display_name payment_account_name from payroll_payment p join payroll_run r on r.id=p.payroll_run_id join cash_bank_account c on c.account_id=p.payment_account_id order by p.paid_on desc,p.created_at desc") : Promise.resolve({rows:[]} as any),
    (can("payroll.pay") || can("salary_advances.manage") || canSeeData) ? query<Row>("select * from cash_bank_balance where is_active=true order by account_kind,display_name") : Promise.resolve({rows:[]} as any),
    can("payroll.view") ? query<Row>("select l.*,e.employee_number,e.first_name,e.last_name from employee_payroll_ledger l join employee e on e.id=l.employee_id order by l.event_date desc,l.ledger_key desc limit 250") : Promise.resolve({rows:[]} as any),
  ]);

  const journals:Row[]=journalsR.rows, roles:Row[]=rolesR.rows, accounts:Row[]=accountsR.rows, jobs:Row[]=jobsR.rows;
  const config:Row=configR.rows[0]??{};
  const employees:Row[]=employeesR.rows, salaryHistory:Row[]=salaryR.rows, advances:Row[]=advancesR.rows, schedules:Row[]=schedulesR.rows;
  const runs:Row[]=runsR.rows, items:Row[]=itemsR.rows, payments:Row[]=paymentsR.rows, cash:Row[]=cashR.rows, ledger:Row[]=ledgerR.rows;
  const activeEmployees=employees.filter((e)=>e.status==="active");
  const outstandingAdvances=advances.reduce((sum,x)=>sum+Number(x.outstanding_amount??0),0);
  const lockedPayable=runs.filter((r)=>r.status==="locked").reduce((sum,x)=>sum+Number(x.net_pay??0),0);
  const setupComplete=Boolean(config.payroll_journal_id)&&roles.length===3&&roles.every((x)=>x.account_id);

  return <main className="app-shell">
    <header className="topbar">
      <div><p className="eyebrow">Advanced payroll</p><h1>Payroll control room</h1><p className="muted">Approvals, locking, payments, accounting mappings and detailed payroll history. Normal employee work starts in Staff.</p></div>
      <div className="top-actions"><a className="button-link secondary-link" href="/staff">Back to Staff</a>{auth.permissions.some((p)=>p.startsWith("accounting."))?<a className="button-link secondary-link" href="/accounting">Accounting</a>:null}{auth.permissions.some((p)=>p.startsWith("rentals."))?<a className="button-link secondary-link" href="/rentals">Rentals</a>:null}</div>
    </header>
    {error?<div className="notice error">{error}</div>:null}{success?<div className="notice success">{success}</div>:null}

    {canSeeData?<section className="status-grid">
      <article className="panel"><p className="eyebrow">Active employees</p><h2>{activeEmployees.length}</h2><p className="muted">{employees.length} employee records retained.</p></article>
      <article className="panel"><p className="eyebrow">Outstanding advances</p><h2>{money(outstandingAdvances,currencySetting)}</h2><p className="muted">Recovered through payroll schedules.</p></article>
      <article className="panel"><p className="eyebrow">Salary payable</p><h2>{money(lockedPayable,currencySetting)}</h2><p className="muted">Locked payroll awaiting payment.</p></article>
      <article className="panel"><p className="eyebrow">Payroll runs</p><h2>{runs.length}</h2><p className="muted">Draft through paid history retained.</p></article>
    </section>:null}

    <section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Accounting setup</p><h2>Payroll posting configuration</h2><p className="muted">Payroll uses the shared double-entry engine and open accounting periods.</p></div><span className="badge">{setupComplete?"Ready":"Setup required"}</span></div>
      <div className="record-grid"><div><small>Payroll journal</small><strong>{journals.find((j)=>j.id===config.payroll_journal_id)?.name??"Not configured"}</strong></div>{roles.map((role)=><div key={role.role_key}><small>{role.name}</small><strong>{role.account_code?role.account_code+" · "+role.account_name:"Not configured"}</strong></div>)}</div>
      {can("accounting.mapping")?<div className="record-grid">
        <form action={configurePayrollJournalAction} className="compact-form"><label>Payroll journal<select name="journal_id" defaultValue={config.payroll_journal_id??""} required><option value="" disabled>Select active journal</option>{journals.map((j)=><option key={j.id} value={j.id}>{j.code} · {j.name}</option>)}</select></label><button type="submit">Save journal</button></form>
        {roles.map((role)=><form action={configurePayrollMappingAction} className="compact-form" key={role.role_key}><input type="hidden" name="role_key" value={role.role_key}/><label>{role.name}<select name="account_id" defaultValue={role.account_id??""} required><option value="" disabled>Select {role.required_category} account</option>{accounts.filter((a)=>a.category===role.required_category).map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name} · {a.currency}</option>)}</select></label><small className="muted">{role.description}</small><button type="submit" className="secondary">Save mapping</button></form>)}
      </div>:null}
    </section>

    {canSeeData?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">People</p><h2>Employees, job titles & salary history</h2><p className="muted">Salary changes create a new effective agreement. Existing salary periods are append-only and cannot be overwritten.</p></div></div>
      {can("employees.manage")?<div className="record-grid">
        <form action={createJobTitleAction} className="compact-form"><h3>New job title</h3><label>Name<input name="name" required/></label><label>Description<input name="description"/></label><button type="submit">Create job title</button></form>
        <form action={createEmployeeAction} className="compact-form"><h3>New employee</h3><label>First name<input name="first_name" required/></label><label>Last name<input name="last_name" required/></label><label>Job title<select name="job_title_id" defaultValue=""><option value="">No job title</option>{jobs.filter((j)=>j.status==="active").map((j)=><option key={j.id} value={j.id}>{j.name}</option>)}</select></label><label>Email<input name="email" type="email"/></label><label>Phone<input name="phone"/></label><label>Address<input name="address"/></label><label>Start date<input type="date" name="start_on" defaultValue={today} required/></label><label>Notes<input name="notes"/></label><button type="submit">Create employee</button></form>
      </div>:null}
      {jobs.length?<div className="table-wrap"><table><thead><tr><th>Job title</th><th>Status</th><th>Maintenance</th></tr></thead><tbody>{jobs.map((j)=><tr key={j.id}><td>{j.name}<div className="muted">{j.description||"—"}</div></td><td><span className="badge">{j.status}</span></td><td>{can("employees.manage")?<form action={updateJobTitleAction} className="inline-form"><input type="hidden" name="job_title_id" value={j.id}/><input name="name" defaultValue={j.name} required/><input name="description" defaultValue={j.description??""}/><select name="status" defaultValue={j.status}><option value="active">Active</option><option value="inactive">Inactive</option></select><button className="secondary" type="submit">Update</button></form>:"—"}</td></tr>)}</tbody></table></div>:null}
      <div className="card-list">{employees.map((e)=>{const history=salaryHistory.filter((s)=>s.employee_id===e.id);return <article className="subcard" key={e.id}>
        <div className="row-between"><div><strong>{e.employee_number} · {e.first_name} {e.last_name}</strong><div className="muted">{e.job_title||"No job title"} · started {iso(e.start_on)}</div></div><span className="badge">{e.status}</span></div>
        <div className="record-grid"><div><small>Current monthly salary</small><strong>{e.current_salary?money(e.current_salary,e.salary_currency):"Not configured"}</strong></div><div><small>Current salary effective</small><strong>{e.salary_effective_from?iso(e.salary_effective_from):"—"}</strong></div><div><small>Contact</small><strong>{[e.phone,e.email].filter(Boolean).join(" · ")||"—"}</strong></div></div>
        {can("employees.manage")?<div className="record-grid">
          <form action={updateEmployeeAction} className="compact-form"><input type="hidden" name="employee_id" value={e.id}/><label>First name<input name="first_name" defaultValue={e.first_name} required/></label><label>Last name<input name="last_name" defaultValue={e.last_name} required/></label><label>Job title<select name="job_title_id" defaultValue={e.job_title_id??""}><option value="">No job title</option>{jobs.map((j)=><option key={j.id} value={j.id}>{j.name}</option>)}</select></label><label>Email<input name="email" type="email" defaultValue={e.email??""}/></label><label>Phone<input name="phone" defaultValue={e.phone??""}/></label><label>Address<input name="address" defaultValue={e.address??""}/></label><label>Start<input type="date" name="start_on" defaultValue={iso(e.start_on)} required/></label><label>End<input type="date" name="end_on" defaultValue={e.end_on?iso(e.end_on):""}/></label><label>Status<select name="status" defaultValue={e.status}><option value="active">Active</option><option value="inactive">Inactive</option><option value="terminated">Terminated</option></select></label><label>Notes<input name="notes" defaultValue={e.notes??""}/></label><button type="submit" className="secondary">Update employee</button></form>
          <form action={createSalaryAgreementAction} className="compact-form"><input type="hidden" name="employee_id" value={e.id}/><h3>New salary agreement</h3><label>Effective from<input type="date" name="effective_from" defaultValue={today} required/></label><label>Monthly salary<input type="number" name="monthly_salary" min="0.01" step="0.01" required/></label><label>Currency<input name="currency" defaultValue={e.salary_currency||currencySetting} maxLength={3} required/></label><label>Notes<input name="notes"/></label><p className="muted">Creates a new history row; previous salary agreements are never edited.</p><button type="submit">Add salary agreement</button></form>
        </div>:null}
        {history.length?<div className="table-wrap"><table><thead><tr><th>Effective from</th><th>Effective to</th><th>Monthly salary</th><th>Notes</th></tr></thead><tbody>{history.map((s)=><tr key={s.id}><td>{iso(s.effective_from)}</td><td>{s.effective_to?iso(s.effective_to):"Current"}</td><td>{money(s.monthly_salary,s.currency)}</td><td>{s.notes||"—"}</td></tr>)}</tbody></table></div>:<p className="muted">No salary agreement yet.</p>}
      </article>})}{!employees.length?<p className="muted">No employees yet.</p>:null}</div>
    </section>:null}

    {canSeeData?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Salary advances</p><h2>Advances & repayment schedules</h2><p className="muted">Advances post to an asset account and due installments are recovered automatically when payroll is locked.</p></div></div>
      {can("salary_advances.manage")?<form action={createSalaryAdvanceAction} className="form-grid create-box"><label>Employee<select name="employee_id" defaultValue="" required><option value="" disabled>Select employee</option>{activeEmployees.map((e)=><option key={e.id} value={e.id}>{e.employee_number} · {e.first_name} {e.last_name}</option>)}</select></label><label>Advance date<input type="date" name="advance_date" defaultValue={today} required/></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Currency<input name="currency" defaultValue={currencySetting} maxLength={3} required/></label><label>Pay from<select name="payment_account_id" defaultValue="" required><option value="" disabled>Select cash/bank</option>{cash.map((c)=><option key={c.account_id} value={c.account_id}>{c.display_name} · {money(c.balance,c.currency)}</option>)}</select></label><label>Installments<input name="installments_count" type="number" min="1" max="120" defaultValue="1" required/></label><label>First repayment<input name="first_repayment_on" type="date" required/></label><label>Reference<input name="reference"/></label><label className="span-2">Notes<input name="notes"/></label><button type="submit">Pay salary advance</button></form>:null}
      <div className="card-list">{advances.map((a)=>{const ss=schedules.filter((s)=>s.salary_advance_id===a.id);return <article className="subcard" key={a.id}><div className="row-between"><div><strong>{a.advance_number} · {a.employee_number} · {a.first_name} {a.last_name}</strong><div className="muted">{iso(a.advance_date)} · {a.payment_account_name}</div></div><span className="badge">{a.status}</span></div><div className="record-grid"><div><small>Original</small><strong>{money(a.amount,a.currency)}</strong></div><div><small>Repaid</small><strong>{money(a.repaid_amount,a.currency)}</strong></div><div><small>Outstanding</small><strong>{money(a.outstanding_amount,a.currency)}</strong></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Due</th><th>Scheduled</th><th>Applied</th><th>Remaining</th></tr></thead><tbody>{ss.map((s)=><tr key={s.id}><td>{s.installment_number}</td><td>{iso(s.due_on)}</td><td>{money(s.amount,a.currency)}</td><td>{money(s.applied_amount,a.currency)}</td><td>{money(Number(s.amount)-Number(s.applied_amount),a.currency)}</td></tr>)}</tbody></table></div>{a.status==="posted"&&Number(a.repaid_amount)===0&&can("salary_advances.manage")?<form action={reverseSalaryAdvanceAction} className="inline-form"><input type="hidden" name="salary_advance_id" value={a.id}/><input type="date" name="reversal_date" defaultValue={today} required/><input name="reason" placeholder="Reversal reason" required/><button type="submit" className="secondary">Reverse advance</button></form>:null}</article>})}{!advances.length?<p className="muted">No salary advances yet.</p>:null}</div>
    </section>:null}

    {canSeeData?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Payroll</p><h2>Payroll runs, approvals, locking & payment</h2><p className="muted">Draft → pending → approved → locked → paid. Locking freezes salary snapshots, adjustments and advance repayments.</p></div></div>
      {can("payroll.manage")?<form action={createPayrollRunAction} className="form-grid create-box"><label>Period start<input type="date" name="period_start" required/></label><label>Period end<input type="date" name="period_end" required/></label><label>Pay date<input type="date" name="pay_date" defaultValue={today} required/></label><label>Currency<input name="currency" defaultValue={currencySetting} maxLength={3} required/></label><label className="span-2">Notes<input name="notes"/></label><button type="submit">Create payroll run</button></form>:null}
      <div className="card-list">{runs.map((r)=>{const runItems=items.filter((i)=>i.payroll_run_id===r.id);const runPayments=payments.filter((p)=>p.payroll_run_id===r.id);return <article className="subcard" key={r.id}>
        <div className="row-between"><div><strong>{r.run_number} · {iso(r.period_start)} → {iso(r.period_end)}</strong><div className="muted">Pay date {iso(r.pay_date)} · {r.employee_count} employee{Number(r.employee_count)===1?"":"s"}</div></div><span className="badge">{r.status}</span></div>
        <div className="record-grid"><div><small>Base salary</small><strong>{money(r.base_salary,r.currency)}</strong></div><div><small>Allowances + bonuses</small><strong>{money(Number(r.allowances)+Number(r.bonuses),r.currency)}</strong></div><div><small>Deductions</small><strong>{money(r.deductions,r.currency)}</strong></div><div><small>Advance repayments</small><strong>{money(r.advance_repayments,r.currency)}</strong></div><div><small>Payroll expense</small><strong>{money(r.payroll_expense,r.currency)}</strong></div><div><small>Net pay</small><strong>{money(r.net_pay,r.currency)}</strong></div></div>
        <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Salary snapshot</th><th>Adjustments</th><th>Advance repayments</th><th>Net</th><th>Payslip</th></tr></thead><tbody>{runItems.map((i)=>{const adjustments=i.adjustments as Row[];const repayments=i.repayments as Row[];const preview=Number(i.base_salary)+adjustments.filter((x)=>x.type==="allowance"||x.type==="bonus").reduce((s,x)=>s+Number(x.amount),0)-adjustments.filter((x)=>x.type==="deduction").reduce((s,x)=>s+Number(x.amount),0);return <tr key={i.id}><td><strong>{i.employee_number} · {i.first_name} {i.last_name}</strong></td><td>{money(i.base_salary,r.currency)}<div className="muted">agreement from {iso(i.salary_effective_from)}</div></td><td>{adjustments.length?adjustments.map((x)=><div key={x.id}>{title(x.type)}: {x.description} · {money(x.amount,r.currency)} {r.status==="draft"&&can("payroll.manage")?<form action={removePayrollAdjustmentAction} className="inline-form"><input type="hidden" name="payroll_adjustment_id" value={x.id}/><button className="secondary" type="submit">Remove</button></form>:null}</div>):"—"}{r.status==="draft"&&can("payroll.manage")?<form action={addPayrollAdjustmentAction} className="compact-form"><input type="hidden" name="payroll_run_item_id" value={i.id}/><select name="adjustment_type" defaultValue="allowance"><option value="allowance">Allowance</option><option value="bonus">Bonus</option><option value="deduction">Deduction</option></select><input name="description" placeholder="Description" required/><input name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required/><button type="submit" className="secondary">Add</button></form>:null}</td><td>{repayments.length?repayments.map((x,idx)=><div key={idx}>{x.advanceNumber} #{x.installment} · {money(x.amount,r.currency)}</div>):r.status==="draft"?<span className="muted">Applied when locked</span>:"—"}</td><td>{r.status==="draft"?money(preview,r.currency):money(i.net_pay,r.currency)}</td><td>{["locked","paid"].includes(r.status)?<a className="button-link secondary-link" href={"/payroll/payslips/"+i.id}>View payslip</a>:"—"}</td></tr>})}</tbody></table></div>
        <div className="inline-form">{r.status==="draft"&&can("payroll.manage")?<form action={submitPayrollRunAction}><input type="hidden" name="payroll_run_id" value={r.id}/><button type="submit">Submit for approval</button></form>:null}{r.status==="pending"&&can("payroll.approve")?<form action={approvePayrollRunAction}><input type="hidden" name="payroll_run_id" value={r.id}/><button type="submit">Approve payroll</button></form>:null}{["pending","approved"].includes(r.status)&&can("payroll.approve")?<form action={returnPayrollRunToDraftAction} className="inline-form"><input type="hidden" name="payroll_run_id" value={r.id}/><input name="reason" placeholder="Reason" required/><button type="submit" className="secondary">Return to draft</button></form>:null}{r.status==="approved"&&can("payroll.lock")?<form action={lockPayrollRunAction}><input type="hidden" name="payroll_run_id" value={r.id}/><button type="submit">Lock + post payroll</button></form>:null}</div>
        {r.status==="locked"&&can("payroll.pay")?<form action={payPayrollRunAction} className="form-grid create-box"><input type="hidden" name="payroll_run_id" value={r.id}/><label>Pay from<select name="payment_account_id" defaultValue="" required><option value="" disabled>Select cash/bank</option>{cash.filter((c)=>c.currency===r.currency).map((c)=><option key={c.account_id} value={c.account_id}>{c.display_name} · {money(c.balance,c.currency)}</option>)}</select></label><label>Paid on<input type="date" name="paid_on" defaultValue={iso(r.pay_date)} required/></label><label>Method<select name="method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="check">Cheque</option><option value="other">Other</option></select></label><label>Cheque no.<input name="cheque_number"/></label><label>Cheque due<input type="date" name="cheque_due_on"/></label><label>Reference<input name="reference"/></label><label className="span-2">Notes<input name="notes"/></label><button type="submit">Pay {money(r.net_pay,r.currency)}</button></form>:null}
        {runPayments.length?<div className="table-wrap"><table><thead><tr><th>Payment</th><th>Date</th><th>Account</th><th>Amount</th><th>Status / reversal</th></tr></thead><tbody>{runPayments.map((p)=><tr key={p.id}><td>{p.payment_number}</td><td>{iso(p.paid_on)}</td><td>{p.payment_account_name}</td><td>{money(p.amount,p.currency)}</td><td><span className="badge">{p.status}</span>{p.status==="posted"&&can("payroll.pay")?<form action={reversePayrollPaymentAction} className="compact-form"><input type="hidden" name="payroll_payment_id" value={p.id}/><input type="date" name="reversal_date" defaultValue={today} required/><input name="reason" placeholder="Reversal reason" required/><button type="submit" className="secondary">Reverse payment</button></form>:null}</td></tr>)}</tbody></table></div>:null}
      </article>})}{!runs.length?<p className="muted">No payroll runs yet.</p>:null}</div>
    </section>:null}

    {can("payroll.view")?<section className="panel section-block"><div className="section-heading"><div><p className="eyebrow">Employee ledger</p><h2>Payroll & advance ledger</h2><p className="muted">Advances, locked payroll, repayments, salary payable and paid salary in one history.</p></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Event</th><th>Reference</th><th>Gross</th><th>Deductions</th><th>Advance + / repayment</th><th>Salary payable</th><th>Salary paid</th></tr></thead><tbody>{ledger.map((l)=><tr key={l.ledger_key}><td>{iso(l.event_date)}</td><td>{l.employee_number} · {l.first_name} {l.last_name}</td><td>{title(l.event_type)}</td><td>{l.reference}</td><td>{money(l.gross_earnings,l.currency)}</td><td>{money(l.deductions,l.currency)}</td><td>{Number(l.advance_increase)>0?"+"+money(l.advance_increase,l.currency):Number(l.advance_repayment)>0?"−"+money(l.advance_repayment,l.currency):"—"}</td><td>{money(l.salary_payable,l.currency)}</td><td>{money(l.salary_paid,l.currency)}</td></tr>)}</tbody></table></div></section>:null}
  </main>;
}
