import Link from "next/link";
import { redirect } from "next/navigation";
import { query } from "@/lib/db";
import { requireUser } from "@/lib/security";
import {
  activateFoodPackageAction,
  addFoodItemPriceAction,
  addFoodPackageItemAction,
  allocateFoodCreditAction,
  allocateFoodPaymentAction,
  archiveFoodPackageAction,
  closeFoodSelectionAction,
  configureFoodIncomeMappingAction,
  createFoodBillAction,
  createFoodItemAction,
  createFoodPackageAction,
  createFoodSelectionAction,
  issueFoodBillAction,
  recordFoodPaymentAction,
  removeFoodPackageItemAction,
  setFoodItemStatusAction,
  voidFoodBillAction,
} from "./actions";

function money(value:unknown,currency="USD"){
  const n=Number(value??0);
  try{return new Intl.NumberFormat("en-US",{style:"currency",currency,minimumFractionDigits:2}).format(n);}
  catch{return currency+" "+n.toFixed(2);}
}
function dateText(value:unknown){return value?String(value).slice(0,10):"—";}

export default async function FoodPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
  const auth=await requireUser();
  const can=(p:string)=>auth.permissions.includes(p);
  if(!["food.view","food.manage","food.billing","food.payments"].some(can))redirect("/forbidden");
  const {error,success}=await searchParams;
  const today=new Date().toISOString().slice(0,10);

  const terms=(await query<any>("select t.id,t.school_year_id,t.sequence,t.name,t.starts_on::text,t.ends_on::text,t.status,y.name as year_name,y.status as year_status from school_term t join school_year y on y.id=t.school_year_id order by y.starts_on desc,t.sequence")).rows;
  const items=(await query<any>("select i.*,p.amount as current_price,p.currency as price_currency,p.effective_from::text,p.effective_to::text from food_item i left join lateral (select amount,currency,effective_from,effective_to from food_item_price p where p.food_item_id=i.id and current_date>=p.effective_from and (p.effective_to is null or current_date<=p.effective_to) order by p.effective_from desc,p.created_at desc limit 1) p on true order by i.status,i.name")).rows;
  const prices=(await query<any>("select p.*,i.name as item_name from food_item_price p join food_item i on i.id=p.food_item_id order by i.name,p.effective_from desc limit 150")).rows;
  const packages=(await query<any>("select p.*,t.name as term_name,t.sequence,y.name as year_name,coalesce(json_agg(json_build_object('food_item_id',i.id,'code',i.code,'name',i.name,'quantity',pi.quantity) order by i.name) filter (where i.id is not null),'[]'::json) as items from food_package p join school_term t on t.id=p.term_id join school_year y on y.id=p.school_year_id left join food_package_item pi on pi.food_package_id=p.id left join food_item i on i.id=pi.food_item_id group by p.id,t.id,y.id order by y.starts_on desc,t.sequence,p.name")).rows;
  const students=(await query<any>("select distinct s.id,s.student_number,concat_ws(' ',s.first_name,s.last_name) as student_name,f.display_name as family_name from student s join family f on f.id=s.family_id join student_enrollment e on e.student_id=s.id and e.status<>'cancelled' join student_term_enrollment te on te.enrollment_id=e.id and te.status<>'cancelled' where s.status in ('active','prospective') order by student_name")).rows;
  const selections=(await query<any>("select s.*,st.student_number,concat_ws(' ',st.first_name,st.last_name) as student_name,f.display_name as family_name,p.code as package_code,p.name as package_name,p.package_kind,t.name as term_name,y.name as year_name from student_food_selection s join student st on st.id=s.student_id join family f on f.id=s.family_id join food_package p on p.id=s.food_package_id join school_term t on t.id=s.term_id join school_year y on y.id=s.school_year_id order by s.created_at desc limit 150")).rows;
  const bills=(await query<any>("select b.*,f.display_name as family_name,st.student_number,concat_ws(' ',st.first_name,st.last_name) as student_name,p.code as package_code,p.name as package_name,p.package_kind from food_bill_balance b join family f on f.id=b.family_id join student st on st.id=b.student_id join food_package p on p.id=b.food_package_id order by b.created_at desc limit 150")).rows;
  const foodPayments=(await query<any>("select a.id,a.amount,a.allocated_on,p.id as payment_id,p.receipt_number,p.received_on,p.status as payment_status,b.id as food_bill_id,b.bill_number,b.currency,st.student_number,concat_ws(' ',st.first_name,st.last_name) as student_name from food_payment_allocation a join payment p on p.id=a.payment_id join food_bill b on b.id=a.food_bill_id join student st on st.id=b.student_id order by a.created_at desc limit 100")).rows;
  const availablePayments=(await query<any>("select p.id,p.receipt_number,p.family_id,p.student_id,p.amount,p.currency,p.received_on,p.unallocated_amount,f.display_name as family_name,concat_ws(' ',s.first_name,s.last_name) as student_name from payment_balance p join family f on f.id=p.family_id left join student s on s.id=p.student_id where p.status='posted' and p.unallocated_amount>0 order by p.received_on desc,p.created_at desc limit 100")).rows;
  const availableCredits=(await query<any>("select c.id,c.credit_note_number,c.family_id,c.student_id,c.amount,c.currency,c.issued_on,c.unallocated_amount,f.display_name as family_name,concat_ws(' ',s.first_name,s.last_name) as student_name from credit_note_balance c join family f on f.id=c.family_id left join student s on s.id=c.student_id where c.status='issued' and c.unallocated_amount>0 order by c.issued_on desc,c.created_at desc limit 100")).rows;
  const cashBank=(await query<any>("select c.account_id,c.account_kind,c.display_name,a.code,a.currency from cash_bank_account c join account a on a.id=c.account_id where c.is_active=true and a.status='active' and a.allow_posting=true order by c.account_kind,c.display_name")).rows;
  const incomeAccounts=(await query<any>("select a.id,a.code,a.name,a.currency from account a join account_type t on t.id=a.account_type_id where t.category='income' and a.status='active' and a.allow_posting=true order by a.code")).rows;
  const foodIncomeMap=(await query<any>("select m.account_id,a.code,a.name,a.currency from accounting_mapping m join account a on a.id=m.account_id where m.role_key='food_income'")).rows[0]??null;
  const kpis=(await query<any>("select (select count(*)::int from student_food_selection where status='active') as active_selections,(select count(*)::int from food_bill where status in ('issued','partially_paid')) as open_bills,(select coalesce(sum(balance_amount),0)::numeric(14,2) from food_bill_balance where status in ('issued','partially_paid')) as outstanding,(select coalesce(sum(total_amount),0)::numeric(14,2) from food_bill where issued_on is not null and status<>'void') as billed,(select coalesce(sum(a.amount),0)::numeric(14,2) from food_payment_allocation a join payment p on p.id=a.payment_id and p.status='posted') as collected")).rows[0];

  const activePackages=packages.filter((x:any)=>x.status==="active");
  const draftPackages=packages.filter((x:any)=>x.status==="draft");
  const openBills=bills.filter((x:any)=>["issued","partially_paid"].includes(x.status));

  return <main className="app-shell">
    <header className="page-header">
      <div>
        <h1>Food</h1>
        <p className="muted">Meal items, packages, what each child is signed up for, and food bills.</p>
      </div>
    </header>
    {error?<div className="notice error">{error}</div>:null}
    {success?<div className="notice success">{success}</div>:null}

    <section className="status-grid">
      <article className="panel"><p className="eyebrow">Selections</p><h2>{kpis.active_selections}</h2><p className="muted">Active student food selections</p></article>
      <article className="panel"><p className="eyebrow">Billed</p><h2>{money(kpis.billed)}</h2><p className="muted">Issued food billing</p></article>
      <article className="panel"><p className="eyebrow">Collected</p><h2>{money(kpis.collected)}</h2><p className="muted">Posted food payments</p></article>
      <article className="panel"><p className="eyebrow">Outstanding</p><h2>{money(kpis.outstanding)}</h2><p className="muted">{kpis.open_bills} open food bills</p></article>
    </section>

    {can("accounting.mapping")?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Accounting</p><h2>Food income mapping</h2></div><span className="badge">{foodIncomeMap?foodIncomeMap.code+" · "+foodIncomeMap.name:"Not configured"}</span></div>
      <p className="muted">Issued food bills debit the existing Accounts Receivable mapping and credit this Food Income account.</p>
      <form action={configureFoodIncomeMappingAction} className="compact-form"><select name="account_id" required defaultValue={foodIncomeMap?.account_id??""}><option value="" disabled>Select income account</option>{incomeAccounts.map((a:any)=><option key={a.id} value={a.id}>{a.code} · {a.name} · {a.currency}</option>)}</select><button type="submit">Save mapping</button></form>
    </section>:null}

    {(can("food.view")||can("food.manage"))?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Catalog</p><h2>Food items & prices</h2></div><span className="badge">{items.filter((x:any)=>x.status==="active").length} active</span></div>
      {can("food.manage")?<div className="split-grid">
        <form action={createFoodItemAction} className="form-grid"><h3 className="span-2">Create food item</h3><label>Code<input name="code" placeholder="LUNCH01" required/></label><label>Name<input name="name" placeholder="Lunch meal" required/></label><label className="span-2">Description<textarea name="description"/></label><button type="submit">Create item</button></form>
        <form action={addFoodItemPriceAction} className="form-grid"><h3 className="span-2">Add price period</h3><label>Item<select name="food_item_id" required defaultValue=""><option value="" disabled>Select item</option>{items.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Price<input name="amount" inputMode="decimal" placeholder="5.00" required/></label><label>Currency<input name="currency" defaultValue="USD" maxLength={3} required/></label><label>Effective from<input name="effective_from" type="date" required/></label><label>Effective to<input name="effective_to" type="date"/></label><button type="submit">Add price</button></form>
      </div>:null}
      <div className="table-wrap"><table><thead><tr><th>Item</th><th>Current price</th><th>Effective</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map((x:any)=><tr key={x.id}><td><strong>{x.code} · {x.name}</strong><small>{x.description||""}</small></td><td>{x.current_price?money(x.current_price,x.price_currency):"No active price"}</td><td>{x.effective_from?dateText(x.effective_from)+" → "+dateText(x.effective_to):"—"}</td><td><span className="badge">{x.status}</span></td><td>{can("food.manage")?<form action={setFoodItemStatusAction} className="compact-form"><input type="hidden" name="food_item_id" value={x.id}/><button className="secondary" name="status" value={x.status==="active"?"inactive":"active"}>{x.status==="active"?"Deactivate":"Activate"}</button></form>:null}</td></tr>)}{!items.length?<tr><td colSpan={5}>No food items yet.</td></tr>:null}</tbody></table></div>
      <details><summary>Price history ({prices.length})</summary><div className="table-wrap"><table><thead><tr><th>Item</th><th>Price</th><th>From</th><th>To</th></tr></thead><tbody>{prices.map((p:any)=><tr key={p.id}><td>{p.item_name}</td><td>{money(p.amount,p.currency)}</td><td>{dateText(p.effective_from)}</td><td>{dateText(p.effective_to)}</td></tr>)}</tbody></table></div></details>
    </section>:null}

    {(can("food.view")||can("food.manage"))?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Packages</p><h2>Daily, weekly, monthly & term packages</h2></div><span className="badge">{activePackages.length} active</span></div>
      {can("food.manage")?<div className="split-grid">
        <form action={createFoodPackageAction} className="form-grid"><h3 className="span-2">Create package</h3><label>Term<select name="term_id" required defaultValue=""><option value="" disabled>Select open term</option>{terms.map((t:any)=><option key={t.id} value={t.id} disabled={t.status==="closed"||t.year_status==="closed"}>{t.year_name} · T{t.sequence} · {t.name}{t.status==="closed"||t.year_status==="closed"?" · CLOSED":""}</option>)}</select></label><label>Type<select name="package_kind" defaultValue="daily"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="term">Term</option></select></label><label>Code<input name="code" placeholder="MONTHLY-LUNCH" required/></label><label>Name<input name="name" placeholder="Monthly lunch package" required/></label><label>Package price<input name="package_price" inputMode="decimal" required/></label><label>Currency<input name="currency" defaultValue="USD" maxLength={3} required/></label><label>Available from<input name="available_from" type="date"/></label><label>Available to<input name="available_to" type="date"/></label><label className="span-2">Notes<textarea name="notes"/></label><button type="submit">Create draft package</button></form>
        <form action={addFoodPackageItemAction} className="form-grid"><h3 className="span-2">Build package contents</h3><label>Draft package<select name="food_package_id" required defaultValue=""><option value="" disabled>Select package</option>{draftPackages.map((p:any)=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>Food item<select name="food_item_id" required defaultValue=""><option value="" disabled>Select item</option>{items.filter((x:any)=>x.status==="active").map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Quantity<input name="quantity" defaultValue="1" inputMode="decimal" required/></label><button type="submit">Add / update item</button></form>
      </div>:null}
      <div className="table-wrap"><table><thead><tr><th>Package</th><th>Term</th><th>Type</th><th>Price</th><th>Contents</th><th>Status</th><th>Actions</th></tr></thead><tbody>{packages.map((p:any)=><tr key={p.id}><td><strong>{p.code} · {p.name}</strong><small>{p.notes||""}</small></td><td>{p.year_name} · T{p.sequence} · {p.term_name}</td><td>{p.package_kind}</td><td>{money(p.package_price,p.currency)}</td><td>{(p.items as any[]).length?(p.items as any[]).map((i:any)=><div key={i.food_item_id}>{i.quantity} × {i.name}{can("food.manage")&&p.status==="draft"?<form action={removeFoodPackageItemAction} className="compact-form"><input type="hidden" name="food_package_id" value={p.id}/><button className="secondary" name="food_item_id" value={i.food_item_id}>Remove</button></form>:null}</div>):"No items"}</td><td><span className="badge">{p.status}</span></td><td>{can("food.manage")&&p.status==="draft"?<form action={activateFoodPackageAction} className="compact-form"><input type="hidden" name="food_package_id" value={p.id}/><button>Activate</button></form>:null}{can("food.manage")&&p.status==="active"?<form action={archiveFoodPackageAction} className="compact-form"><input type="hidden" name="food_package_id" value={p.id}/><button className="secondary">Archive</button></form>:null}</td></tr>)}{!packages.length?<tr><td colSpan={7}>No food packages yet.</td></tr>:null}</tbody></table></div>
    </section>:null}

    {(can("food.view")||can("food.manage"))?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Students</p><h2>Food selections</h2></div></div>
      {can("food.manage")?<form action={createFoodSelectionAction} className="form-grid"><label>Student<select name="student_id" required defaultValue=""><option value="" disabled>Select student</option>{students.map((s:any)=><option key={s.id} value={s.id}>{s.student_number} · {s.student_name} · {s.family_name}</option>)}</select></label><label>Active package<select name="food_package_id" required defaultValue=""><option value="" disabled>Select package</option>{activePackages.map((p:any)=><option key={p.id} value={p.id}>{p.year_name} · T{p.sequence} · {p.code} · {p.name} · {money(p.package_price,p.currency)}</option>)}</select></label><label>Selection quantity<input name="quantity" defaultValue="1" inputMode="decimal" required/></label><label>Starts on<input name="starts_on" type="date" required/></label><label>Ends on<input name="ends_on" type="date" required/></label><label>Notes<input name="notes"/></label><button type="submit">Select package</button></form>:null}
      <div className="table-wrap"><table><thead><tr><th>Student</th><th>Package</th><th>Dates</th><th>Price snapshot</th><th>Status</th><th>Action</th></tr></thead><tbody>{selections.map((s:any)=><tr key={s.id}><td><strong>{s.student_number} · {s.student_name}</strong><small>{s.family_name}</small></td><td>{s.package_code} · {s.package_name}<small>{s.package_kind} · qty {s.quantity}</small></td><td>{dateText(s.starts_on)} → {dateText(s.ends_on)}</td><td>{money(s.unit_price,s.currency)}</td><td><span className="badge">{s.status}</span></td><td>{can("food.manage")&&s.status==="active"?<form action={closeFoodSelectionAction} className="compact-form"><input type="hidden" name="student_food_selection_id" value={s.id}/><button className="secondary" name="status" value="ended">End</button><button className="secondary" name="status" value="cancelled">Cancel</button></form>:null}</td></tr>)}{!selections.length?<tr><td colSpan={6}>No food selections yet.</td></tr>:null}</tbody></table></div>
    </section>:null}

    {(can("food.view")||can("food.billing"))?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Billing</p><h2>Food bills</h2></div><span className="badge">{openBills.length} open</span></div>
      {can("food.billing")?<form action={createFoodBillAction} className="form-grid"><label className="span-2">Selection<select name="student_food_selection_id" required defaultValue=""><option value="" disabled>Select student food selection</option>{selections.filter((s:any)=>s.status!=="cancelled").map((s:any)=><option key={s.id} value={s.id}>{s.student_number} · {s.student_name} · {s.package_code} · {s.package_kind} · {money(s.unit_price,s.currency)}</option>)}</select></label><label>Period start<input name="period_start" type="date" required/></label><label>Period end<input name="period_end" type="date" required/></label><label>Billing units<input name="units" defaultValue="1" inputMode="decimal" required/></label><label>Due on<input name="due_on" type="date" required/></label><label className="span-2">Notes<input name="notes"/></label><button type="submit">Create draft bill</button></form>:null}
      <div className="table-wrap"><table><thead><tr><th>Bill</th><th>Student</th><th>Package / period</th><th>Total</th><th>Paid / credit</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{bills.map((b:any)=><tr key={b.id}><td><strong>{b.bill_number}</strong><small>{b.issued_on?"Issued "+dateText(b.issued_on):"Draft"} · due {dateText(b.due_on)}</small></td><td>{b.student_number} · {b.student_name}<small>{b.family_name}</small></td><td>{b.package_code} · {b.package_name}<small>{dateText(b.period_start)} → {dateText(b.period_end)}</small></td><td>{money(b.total_amount,b.currency)}</td><td>{money(b.paid_amount,b.currency)} / {money(b.credit_amount,b.currency)}</td><td>{money(b.balance_amount,b.currency)}</td><td><span className="badge">{b.status}</span></td><td>{can("food.billing")&&b.status==="draft"?<form action={issueFoodBillAction} className="compact-form"><input type="hidden" name="food_bill_id" value={b.id}/><input name="issued_on" type="date" defaultValue={today} required/><button>Issue</button></form>:null}{can("food.billing")&&["issued","partially_paid","paid"].includes(b.status)?<form action={voidFoodBillAction} className="compact-form"><input type="hidden" name="food_bill_id" value={b.id}/><input name="reversal_date" type="date" defaultValue={today} required/><input name="reason" placeholder="Void reason" required/><button className="secondary">Void</button></form>:null}</td></tr>)}{!bills.length?<tr><td colSpan={8}>No food bills yet.</td></tr>:null}</tbody></table></div>
    </section>:null}

    {(can("food.view")||can("food.payments"))?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Receipts & credits</p><h2>Food collections</h2></div></div>
      {can("food.payments")?<div className="split-grid">
        <form action={recordFoodPaymentAction} className="form-grid"><h3 className="span-2">Record new food payment</h3><label className="span-2">Food bill<select name="food_bill_id" required defaultValue=""><option value="" disabled>Select open bill</option>{openBills.map((b:any)=><option key={b.id} value={b.id}>{b.bill_number} · {b.student_name} · balance {money(b.balance_amount,b.currency)}</option>)}</select></label><label>Amount<input name="amount" inputMode="decimal" required/></label><label>Received on<input name="received_on" type="date" defaultValue={today} required/></label><label>Method<select name="method" defaultValue="cash"><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="check">Cheque</option><option value="other">Other</option></select></label><label>Cash / bank account<select name="payment_account_id" defaultValue=""><option value="">Default mapped payment asset</option>{cashBank.map((a:any)=><option key={a.account_id} value={a.account_id}>{a.display_name} · {a.code} · {a.currency}</option>)}</select></label><label>Cheque number<input name="cheque_number"/></label><label>Cheque due<input name="cheque_due_on" type="date"/></label><label>Reference<input name="reference"/></label><label>Notes<input name="notes"/></label><button type="submit">Post food payment</button></form>
        <div>
          <form action={allocateFoodPaymentAction} className="form-grid"><h3 className="span-2">Use existing parent funds</h3><label>Payment / prepayment<select name="payment_id" required defaultValue=""><option value="" disabled>Select available funds</option>{availablePayments.map((p:any)=><option key={p.id} value={p.id}>{p.receipt_number} · {p.family_name}{p.student_name?" · "+p.student_name:""} · available {money(p.unallocated_amount,p.currency)}</option>)}</select></label><label>Food bill<select name="food_bill_id" required defaultValue=""><option value="" disabled>Select open bill</option>{openBills.map((b:any)=><option key={b.id} value={b.id}>{b.bill_number} · {b.family_name} · {b.student_name} · {money(b.balance_amount,b.currency)}</option>)}</select></label><label>Amount<input name="amount" inputMode="decimal" required/></label><label>Allocated on<input name="allocated_on" type="date" defaultValue={today} required/></label><button type="submit">Allocate payment</button></form>
          <form action={allocateFoodCreditAction} className="form-grid"><h3 className="span-2">Use existing family credit</h3><label>Credit note<select name="credit_note_id" required defaultValue=""><option value="" disabled>Select available credit</option>{availableCredits.map((c:any)=><option key={c.id} value={c.id}>{c.credit_note_number} · {c.family_name}{c.student_name?" · "+c.student_name:""} · available {money(c.unallocated_amount,c.currency)}</option>)}</select></label><label>Food bill<select name="food_bill_id" required defaultValue=""><option value="" disabled>Select open bill</option>{openBills.map((b:any)=><option key={b.id} value={b.id}>{b.bill_number} · {b.family_name} · {b.student_name} · {money(b.balance_amount,b.currency)}</option>)}</select></label><label>Amount<input name="amount" inputMode="decimal" required/></label><label>Allocated on<input name="allocated_on" type="date" defaultValue={today} required/></label><button type="submit">Allocate credit</button></form>
        </div>
      </div>:null}
      <div className="table-wrap"><table><thead><tr><th>Receipt</th><th>Food bill</th><th>Student</th><th>Date</th><th>Applied</th><th>Status</th></tr></thead><tbody>{foodPayments.map((p:any)=><tr key={p.id}><td><Link href={"/receipts/"+p.payment_id}>{p.receipt_number}</Link></td><td>{p.bill_number}</td><td>{p.student_number} · {p.student_name}</td><td>{dateText(p.allocated_on)}</td><td>{money(p.amount,p.currency)}</td><td><span className="badge">{p.payment_status}</span></td></tr>)}{!foodPayments.length?<tr><td colSpan={6}>No food payment receipts yet.</td></tr>:null}</tbody></table></div>
    </section>:null}
  </main>;
}
