import { redirect } from "next/navigation";
import { query } from "@/lib/db";
import { requireUser } from "@/lib/security";
import {
  addReconciliationItemAction,
  completeReconciliationAction,
  configureOperationsJournalAction,
  createCashBankAccountAction,
  createCashBankTransactionAction,
  updateCashBankAccountAction,
  createExpenseAction,
  createParentRefundAction,
  createReconciliationAction,
  createRecurringExpenseAction,
  createSupplierAction,
  createSupplierCreditAction,
  createSupplierInvoiceAction,
  generateRecurringExpensesAction,
  paySupplierInvoiceAction,
  postExpenseAction,
  postSupplierInvoiceAction,
  reviewExpenseAction,
  reverseCashBankTransactionAction,
  reverseExpenseAction,
  reverseParentRefundAction,
  reverseSupplierCreditAction,
  reverseSupplierInvoiceAction,
  reverseSupplierPaymentAction,
  setRecurringExpenseStatusAction,
  submitExpenseAction,
  approveSupplierInvoiceAction,
  updateSupplierAction,
  removeReconciliationItemAction,
} from "./actions";

type Row = Record<string, any>;

function money(amount:unknown,currency="USD"){
  const n=Number(amount??0);
  try{return new Intl.NumberFormat("en-US",{style:"currency",currency,minimumFractionDigits:2,maximumFractionDigits:2}).format(Number.isFinite(n)?n:0);}
  catch{return currency+" "+(Number.isFinite(n)?n:0).toFixed(2);}
}

export default async function OperationsPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
  const auth=await requireUser();
  const {error,success}=await searchParams;
  const can=(p:string)=>auth.permissions.includes(p);
  const allowed=["expenses.view","expenses.manage","expenses.approve","expenses.post","suppliers.view","suppliers.manage","banking.view","banking.manage","banking.reconcile","recurring_expenses.view","recurring_expenses.manage","refunds.manage"].some(can);
  if(!allowed)redirect("/forbidden");

  const today=(await query<{today:string}>("select (now() at time zone 'Asia/Beirut')::date::text as today")).rows[0]?.today??"";
  const currencySetting=(await query<{currency:string|null}>("select value #>> '{}' as currency from app_setting where key='currency'")).rows[0]?.currency??"USD";

  const journals=(await query<Row>("select id,code,name,status from journal where status='active' order by code")).rows;
  const config=(await query<Row>("select operations_journal_id from accounting_configuration where id=1")).rows[0]??{};
  const accounts=(await query<Row>("select a.id,a.code,a.name,a.currency,a.allow_posting,a.status,t.category from account a join account_type t on t.id=a.account_type_id order by a.code")).rows;
  const expenseAccounts=accounts.filter((x)=>x.category==="expense"&&x.status==="active"&&x.allow_posting);
  const assetAccounts=accounts.filter((x)=>x.category==="asset"&&x.status==="active"&&x.allow_posting);
  const postingAccounts=accounts.filter((x)=>x.status==="active"&&x.allow_posting);
  const cashBank=(can("banking.view")||can("banking.manage")||can("expenses.manage")||can("suppliers.manage")||can("refunds.manage"))
    ?(await query<Row>("select * from cash_bank_balance order by account_kind,display_name")).rows:[];

  const suppliers=(can("suppliers.view")||can("suppliers.manage")||can("expenses.manage"))
    ?(await query<Row>("select s.*,ea.code as expense_code,ea.name as expense_name,pa.code as payment_code,pa.name as payment_name from supplier s left join account ea on ea.id=s.default_expense_account_id left join account pa on pa.id=s.default_payment_account_id order by s.name")).rows:[];

  const expenses=(can("expenses.view")||can("expenses.manage")||can("expenses.approve")||can("expenses.post"))
    ?(await query<Row>("select e.*,s.name as supplier_name,ea.code as expense_code,ea.name as expense_name,pa.code as payment_code,pa.name as payment_name,coalesce((select json_agg(json_build_object('id',d.id,'name',d.original_name) order by er.attached_at desc) from expense_receipt er join stored_document d on d.id=er.document_id where er.expense_id=e.id),'[]') as receipts from expense e left join supplier s on s.id=e.supplier_id join account ea on ea.id=e.expense_account_id join account pa on pa.id=e.payment_account_id order by e.incurred_on desc,e.created_at desc limit 200")).rows:[];

  const supplierInvoices=(can("suppliers.view")||can("suppliers.manage")||can("expenses.approve")||can("expenses.post"))
    ?(await query<Row>("select b.*,s.name as supplier_name,a.code as expense_code,a.name as expense_name from supplier_invoice_balance b join supplier s on s.id=b.supplier_id join account a on a.id=b.expense_account_id order by b.invoice_date desc,b.created_at desc limit 200")).rows:[];

  const supplierPayments=can("suppliers.view")||can("suppliers.manage")
    ?(await query<Row>("select p.*,s.name as supplier_name,i.supplier_invoice_number,a.name as payment_account_name from supplier_payment p join supplier s on s.id=p.supplier_id join supplier_invoice i on i.id=p.supplier_invoice_id join account a on a.id=p.payment_account_id order by p.paid_on desc,p.created_at desc limit 100")).rows:[];
  const supplierCredits=can("suppliers.view")||can("suppliers.manage")
    ?(await query<Row>("select c.*,s.name as supplier_name,i.supplier_invoice_number from supplier_credit c join supplier s on s.id=c.supplier_id join supplier_invoice i on i.id=c.supplier_invoice_id order by c.credited_on desc,c.created_at desc limit 100")).rows:[];
  const supplierStatement=can("suppliers.view")
    ?(await query<Row>("select ss.*,s.name as supplier_name from supplier_statement ss join supplier s on s.id=ss.supplier_id order by ss.entry_date desc,ss.occurred_at desc limit 200")).rows:[];

  const families=(can("refunds.manage")||can("payments.view")||can("payments.manage"))
    ?(await query<Row>("select id,family_number,display_name from family order by display_name")).rows:[];
  const students=can("refunds.manage")
    ?(await query<Row>("select id,family_id,student_number,concat_ws(' ',first_name,last_name) as name from student order by first_name,last_name")).rows:[];
  const credits=can("refunds.manage")
    ?(await query<Row>("select c.*,f.family_number,f.display_name from family_credit_balance c join family f on f.id=c.family_id where c.available_credit<>0 order by f.display_name,c.currency")).rows:[];
  const refunds=can("refunds.manage")
    ?(await query<Row>("select r.*,f.family_number,f.display_name,a.name as payment_account_name from parent_refund r join family f on f.id=r.family_id join account a on a.id=r.payment_account_id order by r.refunded_on desc,r.created_at desc limit 100")).rows:[];

  const transactions=can("banking.view")||can("banking.manage")
    ?(await query<Row>("select t.*,a.name as account_name,c.name as contra_name from cash_bank_transaction t join account a on a.id=t.account_id join account c on c.id=t.contra_account_id order by t.transaction_date desc,t.created_at desc limit 150")).rows:[];

  const recurringCategories=can("recurring_expenses.view")||can("recurring_expenses.manage")
    ?(await query<Row>("select * from recurring_expense_category order by sort_order")).rows:[];
  const recurring=can("recurring_expenses.view")||can("recurring_expenses.manage")
    ?(await query<Row>("select r.*,c.name as category_name,s.name as supplier_name,ea.name as expense_account_name,pa.name as payment_account_name from recurring_expense r join recurring_expense_category c on c.category_key=r.category_key left join supplier s on s.id=r.supplier_id join account ea on ea.id=r.expense_account_id join account pa on pa.id=r.payment_account_id order by r.next_due_on,r.name")).rows:[];

  const reconciliations=can("banking.view")||can("banking.reconcile")
    ?(await query<Row>("select r.*,a.name as account_name,a.currency from bank_reconciliation_summary r join account a on a.id=r.account_id order by r.statement_ends_on desc,r.created_at desc limit 100")).rows:[];
  const unreconciledLines=can("banking.reconcile")
    ?(await query<Row>("select gl.journal_line_id,gl.account_id,gl.account_code,gl.account_name,gl.entry_number,gl.posting_date,gl.entry_description,gl.debit,gl.credit,gl.currency from general_ledger gl join cash_bank_account cb on cb.account_id=gl.account_id left join bank_reconciliation_item ri on ri.journal_line_id=gl.journal_line_id where ri.journal_line_id is null order by gl.posting_date desc,gl.entry_number desc limit 400")).rows:[];
  const reconciledLines=can("banking.reconcile")
    ?(await query<Row>("select ri.reconciliation_id,gl.journal_line_id,gl.account_id,gl.entry_number,gl.posting_date,gl.entry_description,gl.debit,gl.credit,gl.currency from bank_reconciliation_item ri join general_ledger gl on gl.journal_line_id=ri.journal_line_id order by gl.posting_date,gl.entry_number")).rows:[];

  return <main className="app-shell">
    <header className="topbar">
      <div><p className="eyebrow">Montikids Montessori Preschool & Nursery</p><h1>Payments, Expenses, Suppliers & Cash/Bank</h1><p className="muted">Every posted operation flows into the double-entry accounting core.</p></div>
      <div className="top-actions"><a className="button-link secondary-link" href="/dashboard">Dashboard</a><a className="button-link secondary-link" href="/billing">Student billing</a><a className="button-link secondary-link" href="/accounting">Accounting</a></div>
    </header>
    {error?<div className="notice error">{error}</div>:null}{success?<div className="notice success">{success}</div>:null}

    <section className="status-grid">
      <article className="panel"><p className="eyebrow">Cash & bank</p><h2>{cashBank.length} accounts</h2><p className="muted">{cashBank.map((x)=>x.display_name+" "+money(x.balance,x.currency)).join(" · ")||"No accounts classified yet."}</p></article>
      <article className="panel"><p className="eyebrow">Expenses</p><h2>{expenses.filter((x)=>x.status==="pending").length} awaiting approval</h2><p className="muted">Posted expenses are immutable and reversed through accounting.</p></article>
      <article className="panel"><p className="eyebrow">Payables</p><h2>{supplierInvoices.filter((x)=>Number(x.balance_amount)>0&&["posted","partially_paid"].includes(x.status)).length} open supplier bills</h2><p className="muted">Supplier invoices, credits and payments feed Accounts Payable.</p></article>
    </section>

    {can("accounting.mapping")?<section className="panel section-block"><div className="section-heading"><div><p className="eyebrow">Accounting connection</p><h2>Operations journal</h2></div></div><form action={configureOperationsJournalAction} className="inline-form"><label>Journal<select name="journal_id" defaultValue={config.operations_journal_id??""} required><option value="" disabled>Select journal</option>{journals.map((j)=><option key={j.id} value={j.id}>{j.code} · {j.name}</option>)}</select></label><button type="submit">Save journal</button></form></section>:null}

    {can("banking.view")||can("banking.manage")?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Bank & cash</p><h2>Cash and bank accounts</h2><p className="muted">These are your normal Step 4 asset accounts, classified for operational use.</p></div></div>
      {can("banking.manage")?<form action={createCashBankAccountAction} className="form-grid create-box">
        <label>Accounting asset account<select name="account_id" defaultValue="" required><option value="" disabled>Select asset account</option>{assetAccounts.filter((a)=>!cashBank.some((c)=>c.account_id===a.id)).map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name} · {a.currency}</option>)}</select></label>
        <label>Type<select name="account_kind" defaultValue="bank"><option value="bank">Bank</option><option value="cash">Cash</option></select></label>
        <label>Display name<input name="display_name" required /></label><label>Bank name<input name="bank_name" /></label><label>Account / wallet identifier<input name="account_identifier" /></label><label>IBAN<input name="iban" /></label><label className="span-2">Notes<input name="notes" /></label><button type="submit">Enable cash/bank account</button>
      </form>:null}
      <div className="table-wrap"><table><thead><tr><th>Account</th><th>Type</th><th>Balance</th><th>Bank / identifier</th><th>Status / maintenance</th></tr></thead><tbody>{cashBank.map((x)=><tr key={x.account_id}><td>{x.account_code} · {x.display_name}</td><td>{x.account_kind}</td><td>{money(x.balance,x.currency)}</td><td>{[x.bank_name,x.account_identifier,x.iban].filter(Boolean).join(" · ")||"—"}</td><td>{can("banking.manage")?<form action={updateCashBankAccountAction} className="compact-form"><input type="hidden" name="account_id" value={x.account_id}/><label>Name<input name="display_name" defaultValue={x.display_name} required/></label><label>Type<select name="account_kind" defaultValue={x.account_kind}><option value="bank">Bank</option><option value="cash">Cash</option></select></label><label>Bank<input name="bank_name" defaultValue={x.bank_name??""}/></label><label>Identifier<input name="account_identifier" defaultValue={x.account_identifier??""}/></label><label>IBAN<input name="iban" defaultValue={x.iban??""}/></label><label>Status<select name="is_active" defaultValue={String(x.is_active)}><option value="true">Active</option><option value="false">Inactive</option></select></label><button type="submit" className="secondary">Update</button></form>:<span className="badge">{x.is_active?"active":"inactive"}</span>}</td></tr>)}</tbody></table></div>
      {can("banking.manage")?<><h3>Transfer, deposit or withdrawal</h3><form action={createCashBankTransactionAction} className="form-grid create-box">
        <label>Type<select name="transaction_kind" defaultValue="transfer"><option value="transfer">Transfer</option><option value="deposit">Deposit</option><option value="withdrawal">Withdrawal</option></select></label>
        <label>Cash/bank account<select name="account_id" defaultValue="" required><option value="" disabled>Select account</option>{cashBank.filter((x)=>x.is_active).map((x)=><option key={x.account_id} value={x.account_id}>{x.display_name} · {x.currency}</option>)}</select></label>
        <label>Contra / destination account<select name="contra_account_id" defaultValue="" required><option value="" disabled>Select account</option>{postingAccounts.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name} · {x.category}</option>)}</select></label>
        <label>Amount<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Currency<input name="currency" defaultValue={currencySetting} maxLength={3} required /></label><label>Date<input name="transaction_date" type="date" defaultValue={today} required /></label><label>Reference<input name="reference" /></label><label>Notes<input name="notes" /></label><button type="submit">Post transaction</button>
      </form></>:null}
      <div className="table-wrap"><table><thead><tr><th>Date</th><th>Number</th><th>Type</th><th>Accounts</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{transactions.map((t)=><tr key={t.id}><td>{String(t.transaction_date).slice(0,10)}</td><td>{t.transaction_number}</td><td>{t.transaction_kind}</td><td>{t.account_name} ↔ {t.contra_name}</td><td>{money(t.amount,t.currency)}</td><td><span className="badge">{t.status}</span></td><td>{can("banking.manage")&&t.status==="posted"?<form action={reverseCashBankTransactionAction} className="inline-form"><input type="hidden" name="transaction_id" value={t.id}/><input type="date" name="reversal_date" defaultValue={today} required/><input name="reason" placeholder="Reason" required/><button className="secondary" type="submit">Reverse</button></form>:null}</td></tr>)}</tbody></table></div>
    </section>:null}

    {can("expenses.view")||can("expenses.manage")||can("expenses.approve")||can("expenses.post")?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Expenses</p><h2>Expense entry, receipts & approvals</h2><p className="muted">Choose any custom Step 4 expense account and the actual cash/bank account that paid it.</p></div></div>
      {can("expenses.manage")?<form action={createExpenseAction} className="form-grid create-box">
        <label>Supplier (optional)<select name="supplier_id" defaultValue=""><option value="">No supplier</option>{suppliers.filter((s)=>s.status==="active").map((s)=><option key={s.id} value={s.id}>{s.supplier_number} · {s.name}</option>)}</select></label>
        <label>Expense account<select name="expense_account_id" defaultValue="" required><option value="" disabled>Select expense account</option>{expenseAccounts.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label>
        <label>Payment account<select name="payment_account_id" defaultValue="" required><option value="" disabled>Select cash/bank</option>{cashBank.filter((x)=>x.is_active).map((x)=><option key={x.account_id} value={x.account_id}>{x.display_name}</option>)}</select></label>
        <label>Amount<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Currency<input name="currency" defaultValue={currencySetting} maxLength={3} required /></label><label>Date<input name="incurred_on" type="date" defaultValue={today} required /></label>
        <label>Method<select name="payment_method" defaultValue="bank_transfer"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="check">Cheque</option><option value="other">Other</option></select></label><label>Cheque number<input name="cheque_number" /></label><label>Cheque due<input name="cheque_due_on" type="date" /></label><label>Reference<input name="reference" /></label><label className="span-2">Notes<input name="notes" /></label>
        <button name="submit_mode" value="draft" type="submit" className="secondary">Save draft</button><button name="submit_mode" value="submit" type="submit">Submit for approval</button>
      </form>:null}
      <div className="card-list">{expenses.map((e)=><article className="subcard" key={e.id}><div className="row-between"><div><strong>{e.expense_number} · {e.expense_name}</strong><div className="muted">{String(e.incurred_on).slice(0,10)} · {e.supplier_name||"No supplier"} · {e.payment_account_name}</div></div><div><strong>{money(e.amount,e.currency)}</strong> <span className="badge">{e.status}</span></div></div><p>{e.notes||e.reference||"No notes"}</p>
        {(e.receipts??[]).length?<div className="chips">{e.receipts.map((r:any)=><a className="chip" key={r.id} href={"/api/expense-receipts/"+r.id}>{r.name}</a>)}</div>:null}
        {can("expenses.manage")&&["draft","pending","approved","posted"].includes(e.status)?<form action={"/api/expenses/"+e.id+"/receipt"} method="post" encType="multipart/form-data" className="inline-form"><label>Attach receipt<input type="file" name="file" required /></label><button type="submit" className="secondary">Upload receipt</button></form>:null}
        <div className="inline-form">
          {can("expenses.manage")&&e.status==="draft"?<form action={submitExpenseAction}><input type="hidden" name="expense_id" value={e.id}/><button type="submit">Submit</button></form>:null}
          {can("expenses.approve")&&e.status==="pending"?<form action={reviewExpenseAction} className="inline-form"><input type="hidden" name="expense_id" value={e.id}/><input name="approval_note" placeholder="Approval note"/><button name="decision" value="approve" type="submit">Approve</button><button name="decision" value="reject" type="submit" className="secondary">Return to draft</button></form>:null}
          {can("expenses.post")&&e.status==="approved"?<form action={postExpenseAction}><input type="hidden" name="expense_id" value={e.id}/><button type="submit">Post to accounting</button></form>:null}
          {can("expenses.post")&&e.status==="posted"?<form action={reverseExpenseAction} className="inline-form"><input type="hidden" name="expense_id" value={e.id}/><input type="date" name="reversal_date" defaultValue={today} required/><input name="reason" placeholder="Reversal reason" required/><button type="submit" className="secondary">Reverse</button></form>:null}
        </div>
      </article>)}</div>
    </section>:null}

    {can("suppliers.view")||can("suppliers.manage")?<section className="panel section-block">
      <div className="section-heading"><div><p className="eyebrow">Suppliers</p><h2>Suppliers, invoices, payables & credits</h2></div></div>
      {can("suppliers.manage")?<form action={createSupplierAction} className="form-grid create-box">
        <label>Name<input name="name" required /></label><label>Contact<input name="contact_name" /></label><label>Email<input type="email" name="email" /></label><label>Phone<input name="phone" /></label><label>Tax number<input name="tax_number" /></label><label>Payment terms days<input name="payment_terms_days" type="number" min="0" defaultValue="0" /></label><label>Default expense account<select name="default_expense_account_id" defaultValue=""><option value="">None</option>{expenseAccounts.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Default payment account<select name="default_payment_account_id" defaultValue=""><option value="">None</option>{cashBank.map((x)=><option key={x.account_id} value={x.account_id}>{x.display_name}</option>)}</select></label><label className="span-2">Address<input name="address" /></label><label className="span-2">Notes<input name="notes" /></label><button type="submit">Create supplier</button>
      </form>:null}
      <div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Contact</th><th>Defaults</th><th>Status / maintenance</th></tr></thead><tbody>{suppliers.map((s)=><tr key={s.id}><td>{s.supplier_number} · {s.name}</td><td>{[s.contact_name,s.phone,s.email].filter(Boolean).join(" · ")||"—"}</td><td>{s.expense_name||"—"} / {s.payment_name||"—"}</td><td>{can("suppliers.manage")?<form action={updateSupplierAction} className="compact-form"><input type="hidden" name="supplier_id" value={s.id}/><label>Name<input name="name" defaultValue={s.name} required/></label><label>Contact<input name="contact_name" defaultValue={s.contact_name??""}/></label><label>Email<input name="email" type="email" defaultValue={s.email??""}/></label><label>Phone<input name="phone" defaultValue={s.phone??""}/></label><label>Address<input name="address" defaultValue={s.address??""}/></label><label>Tax no.<input name="tax_number" defaultValue={s.tax_number??""}/></label><label>Terms<input name="payment_terms_days" type="number" min="0" defaultValue={s.payment_terms_days}/></label><label>Expense<select name="default_expense_account_id" defaultValue={s.default_expense_account_id??""}><option value="">None</option>{expenseAccounts.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Payment<select name="default_payment_account_id" defaultValue={s.default_payment_account_id??""}><option value="">None</option>{cashBank.map((x)=><option key={x.account_id} value={x.account_id}>{x.display_name}</option>)}</select></label><label>Notes<input name="notes" defaultValue={s.notes??""}/></label><label>Status<select name="status" defaultValue={s.status}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button type="submit" className="secondary">Update</button></form>:<span className="badge">{s.status}</span>}</td></tr>)}</tbody></table></div>
      {can("suppliers.manage")?<><h3>New supplier invoice</h3><form action={createSupplierInvoiceAction} className="form-grid create-box">
        <label>Supplier<select name="supplier_id" defaultValue="" required><option value="" disabled>Select supplier</option>{suppliers.filter((s)=>s.status==="active").map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Supplier reference<input name="supplier_reference" /></label><label>Expense account<select name="expense_account_id" defaultValue="" required><option value="" disabled>Select expense account</option>{expenseAccounts.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Currency<input name="currency" defaultValue={currencySetting} maxLength={3} required /></label><label>Invoice date<input name="invoice_date" type="date" defaultValue={today} required /></label><label>Due date<input name="due_on" type="date" defaultValue={today} required /></label><label>Notes<input name="notes" /></label><button type="submit">Create supplier invoice</button>
      </form></>:null}
      <div className="card-list">{supplierInvoices.map((i)=><article className="subcard" key={i.id}><div className="row-between"><div><strong>{i.supplier_invoice_number} · {i.supplier_name}</strong><div className="muted">{i.supplier_reference||"No supplier reference"} · due {String(i.due_on).slice(0,10)} · {i.expense_name}</div></div><div><strong>{money(i.balance_amount,i.currency)} due</strong> <span className="badge">{i.status}</span></div></div><p className="muted">Original {money(i.amount,i.currency)} · paid {money(i.paid_amount,i.currency)} · credits {money(i.credit_amount,i.currency)}</p>
        <div className="inline-form">
          {can("expenses.approve")&&i.status==="draft"?<form action={approveSupplierInvoiceAction}><input type="hidden" name="supplier_invoice_id" value={i.id}/><button type="submit">Approve bill</button></form>:null}
          {can("expenses.post")&&i.status==="approved"?<form action={postSupplierInvoiceAction}><input type="hidden" name="supplier_invoice_id" value={i.id}/><button type="submit">Post payable</button></form>:null}
          {can("expenses.post")&&i.status==="posted"&&Number(i.balance_amount)===Number(i.amount)?<form action={reverseSupplierInvoiceAction} className="inline-form"><input type="hidden" name="supplier_invoice_id" value={i.id}/><input type="date" name="reversal_date" defaultValue={today} required/><input name="reason" placeholder="Reversal reason" required/><button type="submit" className="secondary">Reverse bill</button></form>:null}
        </div>
        {can("suppliers.manage")&&["posted","partially_paid"].includes(i.status)&&Number(i.balance_amount)>0?<div className="record-grid">
          <form action={paySupplierInvoiceAction} className="compact-form"><input type="hidden" name="supplier_invoice_id" value={i.id}/><label>Payment account<select name="payment_account_id" defaultValue="" required><option value="" disabled>Select cash/bank</option>{cashBank.map((x)=><option key={x.account_id} value={x.account_id}>{x.display_name}</option>)}</select></label><label>Amount<input name="amount" type="number" step="0.01" min="0.01" max={i.balance_amount} required/></label><input type="hidden" name="currency" value={i.currency}/><label>Date<input name="paid_on" type="date" defaultValue={today} required/></label><label>Method<select name="method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="check">Cheque</option><option value="other">Other</option></select></label><label>Cheque no.<input name="cheque_number"/></label><label>Cheque due<input type="date" name="cheque_due_on"/></label><label>Reference<input name="reference"/></label><label>Notes<input name="notes"/></label><button type="submit">Pay supplier</button></form>
          <form action={createSupplierCreditAction} className="compact-form"><input type="hidden" name="supplier_invoice_id" value={i.id}/><input type="hidden" name="currency" value={i.currency}/><label>Expense account<select name="expense_account_id" defaultValue={i.expense_account_id} required>{expenseAccounts.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Credit amount<input name="amount" type="number" step="0.01" min="0.01" max={i.balance_amount} required/></label><label>Credit date<input type="date" name="credited_on" defaultValue={today} required/></label><label>Reference<input name="reference"/></label><label>Reason<input name="reason" required/></label><button type="submit" className="secondary">Post supplier credit</button></form>
        </div>:null}
      </article>)}</div>
      {can("suppliers.view")?<><h3>Supplier statement activity</h3><div className="table-wrap"><table><thead><tr><th>Date</th><th>Supplier</th><th>Type</th><th>Reference</th><th>Increase</th><th>Decrease</th><th>Running payable</th></tr></thead><tbody>{supplierStatement.map((x)=><tr key={x.entry_type+":"+x.source_id}><td>{String(x.entry_date).slice(0,10)}</td><td>{x.supplier_name}</td><td>{x.entry_type}</td><td>{x.reference}</td><td>{Number(x.payable_increase)?money(x.payable_increase,x.currency):"—"}</td><td>{Number(x.payable_decrease)?money(x.payable_decrease,x.currency):"—"}</td><td><strong>{money(x.running_payable_balance,x.currency)}</strong></td></tr>)}</tbody></table></div>
      <h3>Recent supplier payments and credits</h3><div className="record-grid">{supplierPayments.map((p)=><article className="subcard" key={p.id}><strong>{p.supplier_payment_number} · {p.supplier_name}</strong><p>{money(p.amount,p.currency)} · {p.supplier_invoice_number} · {p.payment_account_name}</p><span className="badge">{p.status}</span>{can("suppliers.manage")&&p.status==="posted"?<form action={reverseSupplierPaymentAction} className="compact-form"><input type="hidden" name="supplier_payment_id" value={p.id}/><input type="date" name="reversal_date" defaultValue={today} required/><input name="reason" placeholder="Reason" required/><button type="submit" className="secondary">Reverse</button></form>:null}</article>)}{supplierCredits.map((c)=><article className="subcard" key={c.id}><strong>{c.supplier_credit_number} · {c.supplier_name}</strong><p>{money(c.amount,c.currency)} · {c.supplier_invoice_number}</p><span className="badge">{c.status}</span>{can("suppliers.manage")&&c.status==="posted"?<form action={reverseSupplierCreditAction} className="compact-form"><input type="hidden" name="supplier_credit_id" value={c.id}/><input type="date" name="reversal_date" defaultValue={today} required/><input name="reason" placeholder="Reason" required/><button type="submit" className="secondary">Reverse</button></form>:null}</article>)}</div></>:null}
    </section>:null}

    {can("refunds.manage")?<section className="panel section-block"><div className="section-heading"><div><p className="eyebrow">Parent credits</p><h2>Available credits & refunds</h2><p className="muted">Prepayments, overpayments and unused credit notes remain liabilities until allocated or refunded.</p></div></div>
      <div className="table-wrap"><table><thead><tr><th>Family</th><th>Currency</th><th>Payments</th><th>Credits</th><th>Refunded</th><th>Available</th></tr></thead><tbody>{credits.map((x)=><tr key={x.family_id+":"+x.currency}><td>{x.family_number} · {x.display_name}</td><td>{x.currency}</td><td>{money(x.unallocated_payments,x.currency)}</td><td>{money(x.unallocated_credits,x.currency)}</td><td>{money(x.refunded_amount,x.currency)}</td><td><strong>{money(x.available_credit,x.currency)}</strong></td></tr>)}</tbody></table></div>
      <form action={createParentRefundAction} className="form-grid create-box"><label>Family<select name="family_id" defaultValue="" required><option value="" disabled>Select family</option>{families.map((f)=><option key={f.id} value={f.id}>{f.family_number} · {f.display_name}</option>)}</select></label><label>Student (optional)<select name="student_id" defaultValue=""><option value="">Family-level</option>{students.map((s)=><option key={s.id} value={s.id}>{s.student_number} · {s.name}</option>)}</select></label><label>Refund from<select name="payment_account_id" defaultValue="" required><option value="" disabled>Select cash/bank</option>{cashBank.map((x)=><option key={x.account_id} value={x.account_id}>{x.display_name}</option>)}</select></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Currency<input name="currency" defaultValue={currencySetting} maxLength={3} required /></label><label>Date<input name="refunded_on" type="date" defaultValue={today} required /></label><label>Method<select name="method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="check">Cheque</option><option value="other">Other</option></select></label><label>Cheque number<input name="cheque_number" /></label><label>Cheque due<input name="cheque_due_on" type="date" /></label><label>Reference<input name="reference" /></label><label className="span-2">Reason<input name="reason" required /></label><button type="submit">Refund parent credit</button></form>
      <div className="table-wrap"><table><thead><tr><th>Date</th><th>Refund</th><th>Family</th><th>Amount</th><th>Account</th><th>Status</th><th /></tr></thead><tbody>{refunds.map((r)=><tr key={r.id}><td>{String(r.refunded_on).slice(0,10)}</td><td>{r.refund_number}</td><td>{r.family_number} · {r.display_name}</td><td>{money(r.amount,r.currency)}</td><td>{r.payment_account_name}</td><td>{r.status}</td><td>{r.status==="posted"?<form action={reverseParentRefundAction} className="inline-form"><input type="hidden" name="refund_id" value={r.id}/><input type="date" name="reversal_date" defaultValue={today} required/><input name="reason" placeholder="Reason" required/><button type="submit" className="secondary">Reverse</button></form>:null}</td></tr>)}</tbody></table></div>
    </section>:null}

    {can("recurring_expenses.view")||can("recurring_expenses.manage")?<section className="panel section-block"><div className="section-heading"><div><p className="eyebrow">Recurring costs</p><h2>Repeating expenses</h2><p className="muted">Social media, accounting fees, internet, cleaning, software, and any other repeating cost.</p></div></div>
      {can("recurring_expenses.manage")?<><form action={createRecurringExpenseAction} className="form-grid create-box"><label>Name<input name="name" required/></label><label>Category<select name="category_key" defaultValue="" required><option value="" disabled>Select category</option>{recurringCategories.map((x)=><option key={x.category_key} value={x.category_key}>{x.name}</option>)}</select></label><label>Supplier<select name="supplier_id" defaultValue=""><option value="">No supplier</option>{suppliers.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Expense account<select name="expense_account_id" defaultValue="" required><option value="" disabled>Select expense</option>{expenseAccounts.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Payment account<select name="payment_account_id" defaultValue="" required><option value="" disabled>Select cash/bank</option>{cashBank.map((x)=><option key={x.account_id} value={x.account_id}>{x.display_name}</option>)}</select></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Currency<input name="currency" defaultValue={currencySetting} maxLength={3} required/></label><label>Frequency<select name="frequency" defaultValue="monthly"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label><label>Next due<input name="next_due_on" type="date" defaultValue={today} required/></label><label>Payment method<select name="payment_method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="other">Other</option></select></label><label>Reference prefix<input name="reference_prefix"/></label><label>Notes<input name="notes"/></label><button type="submit">Create recurring expense</button></form><form action={generateRecurringExpensesAction} className="inline-form"><label>Generate due expenses through<input name="through_date" type="date" defaultValue={today} required/></label><button type="submit">Generate due expenses</button></form></>:null}
      <div className="table-wrap"><table><thead><tr><th>Name</th><th>Category</th><th>Amount</th><th>Frequency</th><th>Next due</th><th>Status</th><th /></tr></thead><tbody>{recurring.map((r)=><tr key={r.id}><td>{r.name}<div className="muted">{r.supplier_name||"No supplier"} · {r.expense_account_name}</div></td><td>{r.category_name}</td><td>{money(r.amount,r.currency)}</td><td>{r.frequency}</td><td>{String(r.next_due_on).slice(0,10)}</td><td>{r.status}</td><td>{can("recurring_expenses.manage")?<form action={setRecurringExpenseStatusAction} className="inline-form"><input type="hidden" name="recurring_expense_id" value={r.id}/><select name="status" defaultValue={r.status}><option value="active">Active</option><option value="paused">Paused</option><option value="ended">Ended</option></select><button type="submit" className="secondary">Update</button></form>:null}</td></tr>)}</tbody></table></div>
    </section>:null}

    {can("banking.view")||can("banking.reconcile")?<section className="panel section-block"><div className="section-heading"><div><p className="eyebrow">Reconciliation</p><h2>Bank & cash reconciliation</h2><p className="muted">A reconciliation can only complete when its cleared book balance exactly matches the statement ending balance.</p></div></div>
      {can("banking.reconcile")?<form action={createReconciliationAction} className="form-grid create-box"><label>Account<select name="account_id" defaultValue="" required><option value="" disabled>Select cash/bank</option>{cashBank.filter((x)=>x.is_active).map((x)=><option key={x.account_id} value={x.account_id}>{x.display_name}</option>)}</select></label><label>Statement start<input name="statement_starts_on" type="date" defaultValue={today} required/></label><label>Statement end<input name="statement_ends_on" type="date" defaultValue={today} required/></label><label>Statement opening balance<input name="statement_opening_balance" type="number" step="0.01" defaultValue="0.00" required/></label><label>Statement ending balance<input name="statement_ending_balance" type="number" step="0.01" required/></label><label className="span-2">Notes<input name="notes"/></label><button type="submit">Start reconciliation</button></form>:null}
      <div className="card-list">{reconciliations.map((r)=><article className="subcard" key={r.id}><div className="row-between"><div><strong>{r.reconciliation_number} · {r.account_name}</strong><div className="muted">{String(r.statement_starts_on).slice(0,10)} → {String(r.statement_ends_on).slice(0,10)}</div></div><span className="badge">{r.status}</span></div><div className="record-grid"><div><small>Opening balance</small><strong>{money(r.opening_reconciled_balance,r.currency)}</strong></div><div><small>Statement ending</small><strong>{money(r.statement_ending_balance,r.currency)}</strong></div><div><small>Cleared book</small><strong>{money(r.reconciled_book_balance,r.currency)}</strong></div><div><small>Difference</small><strong>{money(r.difference,r.currency)}</strong></div></div>
        {can("banking.reconcile")&&r.status==="draft"?<><form action={addReconciliationItemAction} className="inline-form"><input type="hidden" name="reconciliation_id" value={r.id}/><label>Cleared transaction<select name="journal_line_id" defaultValue="" required><option value="" disabled>Select transaction</option>{unreconciledLines.filter((x)=>x.account_id===r.account_id&&String(x.posting_date).slice(0,10)>=String(r.statement_starts_on).slice(0,10)&&String(x.posting_date).slice(0,10)<=String(r.statement_ends_on).slice(0,10)).map((x)=><option key={x.journal_line_id} value={x.journal_line_id}>{String(x.posting_date).slice(0,10)} · {x.entry_number} · {x.entry_description} · Dr {x.debit} / Cr {x.credit}</option>)}</select></label><button type="submit">Mark cleared</button></form>{reconciledLines.filter((x)=>x.reconciliation_id===r.id).length?<div className="table-wrap"><table><thead><tr><th>Cleared date</th><th>Entry</th><th>Description</th><th>Debit</th><th>Credit</th><th /></tr></thead><tbody>{reconciledLines.filter((x)=>x.reconciliation_id===r.id).map((x)=><tr key={x.journal_line_id}><td>{String(x.posting_date).slice(0,10)}</td><td>{x.entry_number}</td><td>{x.entry_description}</td><td>{money(x.debit,x.currency)}</td><td>{money(x.credit,x.currency)}</td><td><form action={removeReconciliationItemAction}><input type="hidden" name="reconciliation_id" value={r.id}/><input type="hidden" name="journal_line_id" value={x.journal_line_id}/><button type="submit" className="secondary">Unmark</button></form></td></tr>)}</tbody></table></div>:null}<form action={completeReconciliationAction}><input type="hidden" name="reconciliation_id" value={r.id}/><button type="submit" disabled={Number(r.difference)!==0}>Complete reconciliation</button></form></>:null}
      </article>)}</div>
    </section>:null}
  </main>;
}
